spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dealer
    username: root
    password: cristian
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false


