spring:
  datasource:
    url: jdbc:mysql://mysql-172230-0.cloudclusters.net:19998/padrepio
    username: admin
    password: zIQlvlEu
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false